### ISSUE TITLE
pydot dependency

### ISSUE THREAD

**Issue by vigo** [emre/relationships#3]
Hi Emre, I really liked the idea! Just tried some stuff. I have a question, I tried to run:

```
r("Rasmus").get_network("/tmp/x.png")
```

Error poped up:

```
ImportError: You need pydot library to get network functionality.
```

Maybe It would be better to mention on `README.md` or maybe this should come with `pydot` what do you think ?

Again, thanx for the tool :)

**Comment by vigo** [comment]
Also user needs to install `graphviz`:

```
brew install graphviz # for osx
```

helped me out...

**Comment by emre** [comment]
just updated the readme about this. thanks :+1:
